# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # Specify service dependencies here if necessary
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/python:3.7.2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run: git submodule update --recursive --init
      - run:
          name: generate files
          command: |
            . venv/bin/activate
            make publish
#      - run:
#          name: install firebase tools
#          command: npm install -g firebase-tools
#      - run:
#          name: deploy to firebase
#          command: firebase deploy --token "$FIREBASE_TOKEN"

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - persist_to_workspace:
          root: .
          paths:
            - output
            - firebase.json
            - '.firebaserc'
  deploy:
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run: pwd
      - run: ls
      - run:
          name: install firebase tools
          command: npm install -g firebase-tools
      - run:
          name: deploy to firebase
          command: firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
